/* STUDENTS:  DO NOT EDIT THIS FILE.  INSTEAD, CREATE YOUR OWN UNIT TESTS ACCORDING
TO THE LAB DOCUMENT.
*/

// Google Test Framework
#include <gtest/gtest.h>
// Project code from the ../src directory
#include "../src/Duck.h"
//#include <iostream>
#include <string.h>

#ifdef FEEDBACK_TEST_01
// Initial Test for Rubber Duck.  YayYay
TEST(RubberDuckTest,display){
  RubberDuck my_ralph;
  string except_str="I am a Rubber Duck.";
  ASSERT_STREQ(except_str.c_str(),my_ralph.display().c_str()) << "FAIL: display" ;
}
#endif
